name: Build Web

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      binary:
        required: true
        type: string
      run_build_webgl:
        type: string
      run_build_webgpu:
        type: string
      optimize_wasm:
        type: string  
      web_graphic_api:
        type: string
      run_publish_github_pages:
        type: string
     

jobs:
  build-webgl:
    if: inputs.run_build_webgl == 'true'
    name: webgl
    env:
      platform: webgl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: install wasm-bindgen-cli
        run: |
          cargo install wasm-bindgen-cli

      - name: install wasm-opt
        if: inputs.optimize_wasm == 'true'
        run: | 
          cargo install wasm-opt

      - name: Build
        run: |
          cargo build --release --target wasm32-unknown-unknown

      - name: Set file name
        id: set_file_name
        run: |
          echo "file_name=${{ inputs.binary }}_${{ inputs.tag }}_${{ env.platform }}" >> "$GITHUB_OUTPUT"

      - name: Prepare package
        run: |
          wasm-bindgen --no-typescript --out-name bevy_game --out-dir wasm --target web target/wasm32-unknown-unknown/release/${{ inputs.binary }}.wasm
          cp -r assets wasm/

      - name: Optimize wasm
        if: inputs.optimize_wasm == 'true'
        run: |
          wasm-opt -Oz --output wasm/bevy_game_bg.wasm wasm/bevy_game_bg.wasm

      - name: Upload github-page to artifacts
        if: inputs.run_publish_github_pages == 'true' && inputs.web_graphic_api == 'webgl'
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./wasm
          retention-days: 1

      - name: Package as a zip
        working-directory: ./wasm
        run: |
          zip --recurse-paths ../${{ steps.set_file_name.outputs.file_name  }}.zip .

      - name: Upload binaries to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.platform }}
          path: ${{ steps.set_file_name.outputs.file_name  }}.zip
          retention-days: 1

  build-webgpu:
    if: inputs.run_build_webgpu == 'true'
    name: webgpu
    env:
      platform: webgpu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: install wasm-bindgen-cli
        run: |
          cargo install wasm-bindgen-cli

      - name: install wasm-opt
        if: inputs.optimize_wasm == 'true'
        run: | 
          cargo install wasm-opt

      - name: Build
        run: |
          RUSTFLAGS="--cfg=web_sys_unstable_apis" cargo build --release --target wasm32-unknown-unknown --no-default-features --features "webgpu"

      - name: Set file name
        id: set_file_name
        run: |
          echo "file_name=${{ inputs.binary }}_${{ inputs.tag }}_${{ env.platform }}" >> "$GITHUB_OUTPUT"

      - name: Prepare package
        run: |
          wasm-bindgen --no-typescript --out-name bevy_game --out-dir wasm --target web target/wasm32-unknown-unknown/release/${{ inputs.binary }}.wasm
          cp -r assets wasm/

      - name: Optimize wasm
        if: inputs.optimize_wasm == 'true'
        run: |
          wasm-opt -Oz --output wasm/bevy_game_bg.wasm wasm/bevy_game_bg.wasm

      - name: Upload github-page to artifacts
        if: inputs.run_publish_github_pages == 'true' && inputs.web_graphic_api == 'webgpu'
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./wasm
          retention-days: 1

      - name: Package as a zip
        working-directory: ./wasm
        run: |
          zip --recurse-paths ../${{ steps.set_file_name.outputs.file_name  }}.zip .

      - name: Upload binaries to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.platform }}
          path: ${{ steps.set_file_name.outputs.file_name  }}.zip
          retention-days: 1